---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-test-script
  namespace: default
data:
  test-connectivity.sh: |
    #!/bin/bash
    
    # Color codes for output
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color
    
    # Counters
    CRITICAL_PASS=0
    CRITICAL_FAIL=0
    RECOMMENDED_PASS=0
    RECOMMENDED_FAIL=0
    OPTIONAL_PASS=0
    OPTIONAL_FAIL=0
    
    # Arrays to store failed URLs
    CRITICAL_FAILED=()
    RECOMMENDED_FAILED=()
    OPTIONAL_FAILED=()
    
    echo "========================================================================="
    echo "TIBCO Platform Connectivity Test Report"
    echo "Platform: Azure Kubernetes Service (AKS)"
    echo "Date: $(date)"
    echo "Hostname: $(hostname)"
    echo "========================================================================="
    echo ""
    
    # Function to test URL connectivity
    test_url() {
        local url=$1
        local category=$2
        local timeout=5
        
        # Test with curl
        if curl -s -o /dev/null -w "%{http_code}" --max-time $timeout --connect-timeout $timeout "$url" > /tmp/http_code 2>/dev/null; then
            http_code=$(cat /tmp/http_code)
            # Accept 2xx, 3xx, 4xx as success (connection established)
            if [[ $http_code -ge 200 ]] && [[ $http_code -lt 500 ]]; then
                echo -e "${GREEN}✓ PASS${NC} $url (HTTP $http_code)"
                return 0
            else
                echo -e "${RED}✗ FAIL${NC} $url (HTTP $http_code)"
                return 1
            fi
        else
            echo -e "${RED}✗ FAIL${NC} $url (Connection timeout/failed)"
            return 1
        fi
    }
    
    echo "========================================================================="
    echo "SECTION 1: CRITICAL ENDPOINTS (Must be accessible)"
    echo "========================================================================="
    echo ""
    
    echo "--- TIBCO Container Registry (CRITICAL) ---"
    for url in \
        "https://csgprduswrepoedge.jfrog.io"
    do
        if test_url "$url" "CRITICAL"; then
            ((CRITICAL_PASS++))
        else
            ((CRITICAL_FAIL++))
            CRITICAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "--- TIBCO Helm Charts (CRITICAL) ---"
    for url in \
        "https://tibcosoftware.github.io/tp-helm-charts" \
        "https://tibcosoftware.github.io/tp-helm-charts/index.yaml"
    do
        if test_url "$url" "CRITICAL"; then
            ((CRITICAL_PASS++))
        else
            ((CRITICAL_FAIL++))
            CRITICAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "--- Third-Party Helm Charts (CRITICAL) ---"
    for url in \
        "https://charts.jetstack.io" \
        "https://charts.jetstack.io/index.yaml" \
        "https://helm.elastic.co" \
        "https://kubernetes-sigs.github.io/external-dns" \
        "https://prometheus-community.github.io/helm-charts"
    do
        if test_url "$url" "CRITICAL"; then
            ((CRITICAL_PASS++))
        else
            ((CRITICAL_FAIL++))
            CRITICAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "--- Container Registries (CRITICAL) ---"
    for url in \
        "https://docker.io" \
        "https://index.docker.io" \
        "https://ghcr.io"
    do
        if test_url "$url" "CRITICAL"; then
            ((CRITICAL_PASS++))
        else
            ((CRITICAL_FAIL++))
            CRITICAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "--- Azure Services (CRITICAL) ---"
    for url in \
        "https://management.azure.com" \
        "https://login.microsoftonline.com" \
        "https://disk.csi.azure.com" \
        "https://file.csi.azure.com"
    do
        if test_url "$url" "CRITICAL"; then
            ((CRITICAL_PASS++))
        else
            ((CRITICAL_FAIL++))
            CRITICAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "========================================================================="
    echo "SECTION 2: RECOMMENDED ENDPOINTS (Highly recommended)"
    echo "========================================================================="
    echo ""
    
    echo "--- Microsoft Container Registry (RECOMMENDED) ---"
    for url in \
        "https://mcr.microsoft.com"
    do
        if test_url "$url" "RECOMMENDED"; then
            ((RECOMMENDED_PASS++))
        else
            ((RECOMMENDED_FAIL++))
            RECOMMENDED_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "--- Kubernetes and GitHub (RECOMMENDED) ---"
    for url in \
        "https://k8s.io" \
        "https://kubernetes.io" \
        "https://github.com" \
        "https://raw.githubusercontent.com"
    do
        if test_url "$url" "RECOMMENDED"; then
            ((RECOMMENDED_PASS++))
        else
            ((RECOMMENDED_FAIL++))
            RECOMMENDED_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "========================================================================="
    echo "SECTION 3: OPTIONAL ENDPOINTS (For documentation and troubleshooting)"
    echo "========================================================================="
    echo ""
    
    echo "--- Documentation Sites (OPTIONAL) ---"
    for url in \
        "https://learn.microsoft.com" \
        "https://prometheus.io" \
        "https://opentelemetry.io" \
        "https://elastic.co" \
        "https://ubuntu.com"
    do
        if test_url "$url" "OPTIONAL"; then
            ((OPTIONAL_PASS++))
        else
            ((OPTIONAL_FAIL++))
            OPTIONAL_FAILED+=("$url")
        fi
    done
    echo ""
    
    echo "========================================================================="
    echo "CONNECTIVITY TEST SUMMARY"
    echo "========================================================================="
    echo ""
    
    TOTAL_CRITICAL=$((CRITICAL_PASS + CRITICAL_FAIL))
    TOTAL_RECOMMENDED=$((RECOMMENDED_PASS + RECOMMENDED_FAIL))
    TOTAL_OPTIONAL=$((OPTIONAL_PASS + OPTIONAL_FAIL))
    TOTAL_TESTS=$((TOTAL_CRITICAL + TOTAL_RECOMMENDED + TOTAL_OPTIONAL))
    TOTAL_PASS=$((CRITICAL_PASS + RECOMMENDED_PASS + OPTIONAL_PASS))
    TOTAL_FAIL=$((CRITICAL_FAIL + RECOMMENDED_FAIL + OPTIONAL_FAIL))
    
    echo "CRITICAL Endpoints:"
    echo "  Total: $TOTAL_CRITICAL"
    echo -e "  ${GREEN}Passed: $CRITICAL_PASS${NC}"
    echo -e "  ${RED}Failed: $CRITICAL_FAIL${NC}"
    echo ""
    
    echo "RECOMMENDED Endpoints:"
    echo "  Total: $TOTAL_RECOMMENDED"
    echo -e "  ${GREEN}Passed: $RECOMMENDED_PASS${NC}"
    echo -e "  ${YELLOW}Failed: $RECOMMENDED_FAIL${NC}"
    echo ""
    
    echo "OPTIONAL Endpoints:"
    echo "  Total: $TOTAL_OPTIONAL"
    echo -e "  ${GREEN}Passed: $OPTIONAL_PASS${NC}"
    echo -e "  ${YELLOW}Failed: $OPTIONAL_FAIL${NC}"
    echo ""
    
    echo "========================================================================="
    echo "OVERALL STATISTICS"
    echo "========================================================================="
    echo "Total Tests: $TOTAL_TESTS"
    echo -e "${GREEN}Total Passed: $TOTAL_PASS${NC}"
    echo -e "${RED}Total Failed: $TOTAL_FAIL${NC}"
    PASS_RATE=$(awk "BEGIN {printf \"%.2f\", ($TOTAL_PASS/$TOTAL_TESTS)*100}")
    echo "Pass Rate: ${PASS_RATE}%"
    echo ""
    
    # Show failed endpoints by category
    if [ ${#CRITICAL_FAILED[@]} -gt 0 ]; then
        echo "========================================================================="
        echo -e "${RED}CRITICAL FAILURES (IMMEDIATE ACTION REQUIRED)${NC}"
        echo "========================================================================="
        for url in "${CRITICAL_FAILED[@]}"; do
            echo -e "  ${RED}✗${NC} $url"
        done
        echo ""
    fi
    
    if [ ${#RECOMMENDED_FAILED[@]} -gt 0 ]; then
        echo "========================================================================="
        echo -e "${YELLOW}RECOMMENDED FAILURES (Should be addressed)${NC}"
        echo "========================================================================="
        for url in "${RECOMMENDED_FAILED[@]}"; do
            echo -e "  ${YELLOW}⚠${NC} $url"
        done
        echo ""
    fi
    
    if [ ${#OPTIONAL_FAILED[@]} -gt 0 ]; then
        echo "========================================================================="
        echo -e "${BLUE}OPTIONAL FAILURES (May impact troubleshooting)${NC}"
        echo "========================================================================="
        for url in "${OPTIONAL_FAILED[@]}"; do
            echo -e "  ${BLUE}ℹ${NC} $url"
        done
        echo ""
    fi
    
    # Recommendations
    echo "========================================================================="
    echo "RECOMMENDATIONS"
    echo "========================================================================="
    
    if [ $CRITICAL_FAIL -eq 0 ]; then
        echo -e "${GREEN}✓${NC} All CRITICAL endpoints are accessible"
    else
        echo -e "${RED}✗${NC} $CRITICAL_FAIL CRITICAL endpoint(s) failed - TIBCO Platform deployment may fail"
        echo "  Action: Contact network/security team to open firewall rules"
    fi
    
    if [ $RECOMMENDED_FAIL -eq 0 ]; then
        echo -e "${GREEN}✓${NC} All RECOMMENDED endpoints are accessible"
    else
        echo -e "${YELLOW}⚠${NC} $RECOMMENDED_FAIL RECOMMENDED endpoint(s) failed - Some features may not work"
        echo "  Action: Review firewall rules for RECOMMENDED endpoints"
    fi
    
    if [ $OPTIONAL_FAIL -gt 0 ]; then
        echo -e "${BLUE}ℹ${NC} $OPTIONAL_FAIL OPTIONAL endpoint(s) failed - Documentation access may be limited"
    fi
    
    echo ""
    echo "========================================================================="
    echo "NEXT STEPS"
    echo "========================================================================="
    
    if [ $CRITICAL_FAIL -gt 0 ]; then
        echo "1. URGENT: Open firewall rules for CRITICAL endpoints"
        echo "2. Refer to: docs/firewall-requirements.md for complete firewall rules"
        echo "3. Use Section 8 (NSG Rules) or Section 9 (Azure Firewall Rules) for configuration"
        echo "4. Re-run this test after firewall changes: kubectl delete job connectivity-test && kubectl apply -f connectivity-test-job.yaml"
    elif [ $RECOMMENDED_FAIL -gt 0 ]; then
        echo "1. Review and open firewall rules for RECOMMENDED endpoints"
        echo "2. Deployment can proceed but some features may be unavailable"
        echo "3. Refer to: docs/firewall-requirements.md"
    else
        echo "1. ✓ All required connectivity checks passed"
        echo "2. Proceed with TIBCO Platform deployment"
        echo "3. Monitor connectivity during deployment"
    fi
    
    echo ""
    echo "========================================================================="
    echo "Test completed at: $(date)"
    echo "========================================================================="
    
    # Exit with error code if critical endpoints failed
    if [ $CRITICAL_FAIL -gt 0 ]; then
        echo ""
        echo -e "${RED}EXITING WITH ERROR CODE 1 - CRITICAL ENDPOINTS FAILED${NC}"
        exit 1
    elif [ $RECOMMENDED_FAIL -gt 0 ]; then
        echo ""
        echo -e "${YELLOW}EXITING WITH WARNING CODE 2 - RECOMMENDED ENDPOINTS FAILED${NC}"
        exit 2
    else
        echo ""
        echo -e "${GREEN}EXITING WITH SUCCESS CODE 0 - ALL CHECKS PASSED${NC}"
        exit 0
    fi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: connectivity-test
  namespace: default
  labels:
    app: connectivity-test
    component: network-validation
spec:
  # Keep job history for debugging
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400  # Keep for 24 hours after completion
  
  template:
    metadata:
      labels:
        app: connectivity-test
        component: network-validation
    spec:
      restartPolicy: Never
      
      # Use a container with curl
      containers:
      - name: connectivity-tester
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            apk add --no-cache bash
            bash /scripts/test-connectivity.sh
        
        # Mount the script
        volumeMounts:
        - name: test-script
          mountPath: /scripts
          readOnly: true
        
        # Resource limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      volumes:
      - name: test-script
        configMap:
          name: connectivity-test-script
          defaultMode: 0755
